[project]
name = "multiplex-imaging-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "igraph>=0.11.9",
    "ipywidgets>=8.1.7",
    "leidenalg>=0.10.2",
    "scanpy>=1.11.4",
]
